We should start with learning how to create and manage some basic functions related to tensors in PyTorch.



*Installation of PyTorch please refer to GET STARTED: https://pytorch.org/get-started/locally/*

*Refrerece video: https://www.youtube.com/watch?v=exaWOE8jvy8&list=PLqnslRFeH2UrcDBWF5mfPGpqQDSta6VK4&index=4*

*(This YouTube PyTorch tutorial is recommended)*

In [ ]:
import torch


""" with torch.empty, we can easily create empty torch tensors."""
x = torch.empty(3)
print(f'tensor of shape (3): {x}')
# this print a 1D tensor with shape 3


""" The first entry designates the shape of the tensor.
We can also assign the data type using `dtype` as below"""
x = torch.empty(3,2, dtype=torch.float32)
print(f'tensor of shape (3,2): {x}')
# This print is an empty tensor with shape (3,2)


""" To check the data type of a torch.tensor, we can simply call `.dtype`"""
print(f'the data type of x is now: {x.dtype}')
""" On the other hand, we can check the shape of x with `.size()`"""
print(f'the shape of x is {x.size()}')
# Note that we can also call x.shape to find the same result


""" Besides `.empty`, tensors can be initiated differently"""
x = torch.rand(2, 2, 2, 3)
print(f'example of rand: {x}')
# `.rand` gives random value components
x = torch.ones(2, 2, 2)
print(f'example with ones: {x}')
# `.ones` fills tensor with given shaped with ones
# Note that we can of course incorporate the `dtype=` method too

""" To create a tensor with given values, we simply do"""
ex1 = torch.tensor([1,2,3])
ex2 = torch.tensor([[1], [2], [3]])
ex3 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'ex1:\n {ex1} with shape {ex1.size()}')
print(f'ex2:\n {ex2} with shape {ex2.size()}')
print(f'ex3:\n {ex3} with shape {ex3.size()}')


tensor of shape (3): tensor([0., 0., 0.])
tensor of shape (3,2): tensor([[-7.6959e-29,  4.4196e-41],
        [-2.2742e+26,  3.1040e-41],
        [ 4.4842e-44,  0.0000e+00]])
the data type of x is now: torch.float32
the shape of x is torch.Size([3, 2])
example of rand: tensor([[[[0.4720, 0.8672, 0.0880],
          [0.3601, 0.5712, 0.7570]],

         [[0.9826, 0.8467, 0.9302],
          [0.7855, 0.7775, 0.1663]]],


        [[[0.6910, 0.8895, 0.9056],
          [0.3281, 0.3815, 0.5234]],

         [[0.7598, 0.5422, 0.2629],
          [0.7194, 0.3346, 0.4623]]]])
example with ones: tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
ex1:
 tensor([1, 2, 3]) with shape torch.Size([3])
ex2:
 tensor([[1],
        [2],
        [3]]) with shape torch.Size([3, 1])
ex3:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) with shape torch.Size([3, 3])


In [ ]:
"""
Now we can learn some basic operation
"""
x = torch.tensor([1,2,3])
y = torch.tensor([1,2,3])

## Element-ment wise addition
z = x + y
print(z)
z = torch.add(x, y) # equivilent to x + y
print(z)

# we can also do
y.add_(x)
print(y)
""" IMPORTANT:
In PyTorch, any function with a trailing underscore ("_"), such as .add_(),
is an in-place operation. This means it directly modifies the data
of the tensor it is called on, rather than creating a new tensor with
the result. Be cautious when using in-place operations, as they change
the content of the original tensor and may interfere with the
`computational graph` for automatic differentiation."""

# compare with the in-place version, we can do out-of-place addition
z = y.add(x)
""" When using add(), PyTorch allocates new memory for the result,
making it a separate object from the original tensors.
In such cases, the original y can still exist in the computational graph
and can still be tracked later by PyTorch's autograd system.

Topics related to the computational graph and autograd will come later.
"""


## substraction
y = torch.tensor([1,2,3]) # reset y
z = x - y
print(z)
z = torch.sub(x,y)
print(z)
# or
y.sub_(x)
print(y)

## element wise multiplication and division are similar
y = torch.tensor([1,2,3])

z = x * y
z = torch.mul(x, y)
print(z)

z = x / y
z = torch.div(x, y)
print(z)

# of course, we have `.mul_()` or `.div_()` methods here too
"""Exercise: play with in-place multiplication and division.

Do you find an error? Why?
hint: checking `.dtype`.
"""



tensor([2, 4, 6])
tensor([2, 4, 6])
tensor([2, 4, 6])
tensor([0, 0, 0])
tensor([0, 0, 0])
tensor([0, 0, 0])
tensor([1, 4, 9])
tensor([1., 1., 1.])


'Exercise: play with in-place multiplication and division.'

In [ ]:
"""
Slicing
"""
import torch

x = torch.rand(5, 5)  # 5x5 tensor of random values
print(x)
print(x[:, 0])  # Run through all rows at column 0 (first column)
print(x[2:, 0])  # Starting from the 3rd row onward, for column 0
print(x[0, :3])  # Row 0, up to (but not including) the 4rd column

"""
Note: When you create a tensor with 2 dimensions, it is a 2D tensor.
You can think of it as x[i, j], where the first index i represents the row
and the second index j represents the column.
"""

"""
Slicing itself is not an in-place operation but a view of the original tensor.
It shares the same memory as the original tensor.
Following are some demonstrations of operations.
"""

### Example: Slicing creates a view
# Original tensor
x = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0])

# Slicing the tensor (creates a view)
y = x[1:4]

# Modifying the slice (not in-place)
y = y + 1

print("Original x:", x)  # x remains unchanged
print("Slice y:", y)     # y is a new tensor with the result of the operation


### Example: In-place Modification of a Slice
# Original tensor
x = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0])

# Slicing the tensor (creates a view)
y = x[1:4]

# In-place modification of the slice
y.add_(1)

print("Original x:", x)  # x will be modified
print("Slice y:", y)     # y also reflects the in-place modification

tensor([[0.8835, 0.9454, 0.3013, 0.1823, 0.0865],
        [0.7772, 0.3688, 0.4386, 0.4313, 0.9339],
        [0.9562, 0.8745, 0.2060, 0.2765, 0.7073],
        [0.9373, 0.2182, 0.6257, 0.0107, 0.7238],
        [0.8941, 0.6045, 0.2227, 0.2359, 0.9832]])
tensor([0.8835, 0.7772, 0.9562, 0.9373, 0.8941])
tensor([0.9562, 0.9373, 0.8941])
tensor([0.8835, 0.9454, 0.3013])
Original x: tensor([1., 2., 3., 4., 5.])
Slice y: tensor([3., 4., 5.])
Original x: tensor([1., 3., 4., 5., 5.])
Slice y: tensor([3., 4., 5.])


In [ ]:
"""
Reshaping a tensor with `.view`
"""
x = torch.rand(4,4)
print(x)
# We can use the view method to reshape a tensor
# it is like "viewing" the components in a different way
# remember what we have just discussed about "the view of an object"

y = x.view(16)
print(y)
# we can designate what kind of shape we want for viewing this object
# in this example, we simply ask for a 1D, 16-component vector.

# we can also do
y = x.view(8, 2)
print(y)

# The number of components should be consistent.
# We could also let the function assign the dimensions automatically
# by inputting -1:

y = x.view(2, -1)
print(f'\n{y}, \nautomatically given a view of shape {y.shape}')

tensor([[0.9946, 0.8823, 0.5472, 0.9659],
        [0.4512, 0.4721, 0.8671, 0.5193],
        [0.4406, 0.0111, 0.4736, 0.6988],
        [0.4123, 0.8340, 0.8374, 0.5683]])
tensor([0.9946, 0.8823, 0.5472, 0.9659, 0.4512, 0.4721, 0.8671, 0.5193, 0.4406,
        0.0111, 0.4736, 0.6988, 0.4123, 0.8340, 0.8374, 0.5683])
tensor([[0.9946, 0.8823],
        [0.5472, 0.9659],
        [0.4512, 0.4721],
        [0.8671, 0.5193],
        [0.4406, 0.0111],
        [0.4736, 0.6988],
        [0.4123, 0.8340],
        [0.8374, 0.5683]])

tensor([[0.9946, 0.8823, 0.5472, 0.9659, 0.4512, 0.4721, 0.8671, 0.5193],
        [0.4406, 0.0111, 0.4736, 0.6988, 0.4123, 0.8340, 0.8374, 0.5683]]), 
automatically given a view of shape torch.Size([2, 8])


In [ ]:
"""
Creating a Tensor from a NumPy Array

Transforming data between NumPy and PyTorch is a common practice.

Typically, many calculations that do not require autograd, such as numerical
simulations of physical environments, are done using NumPy. On the other hand,
we use PyTorch when we need to leverage the power of autograd, computational
graphs, and the ability to perform computations on GPUs for tasks like training
models. These differences will become clearer as we explore how PyTorch aids in
training models with large numbers of parameters in later tutorials.
"""


'\nCreating a Tensor from a NumPy Array\n\nTransforming data between NumPy and PyTorch is a common practice.\n\nTypically, many calculations that do not require autograd, such as numerical \nsimulations of physical environments, are done using NumPy. On the other hand, \nwe use PyTorch when we need to leverage the power of autograd and computational \ngraphs for tasks like training models. These differences will become clearer as \nwe explore how PyTorch aids in training models with large numbers of parameters \nin later tutorials.\n'

In [ ]:
import numpy as np

a = torch.ones(5)
print(a)

# to transform a torch.tensor to np.array we simply do:
b = a.numpy()
print(type(a)) # for torch.tensor, you can also check it with a.dtype (return "torch.float32")
print(type(b)) # but here, b.dtype simply return "float32"
print(b)

"""
NOTE that if the data is located on the CPU (by default, they are on the CPU),
both objects will share the same memory location.

--> If we change one of them in-placed, another one will be changed too:
"""
a.add_(1)
print(a)
print(b)

# Transform from np.array to torch.tensor:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

# Exercise: Try observing how torch.tensor and numpy.array data are printed

"""
Same here, they shared the same memory location:
"""
a += 1    # Note: a += 1 is in-place operation; a = a + 1 is out-of-place
print(a)
print(b)


"""
What if the data is on the GPU?

To avoid confusion, we shall introduce how to move data from the CPU to the GPU later.
Yet a simple fact is that NumPy cannot handle data on the GPU, so we always have
to move torch.tensor back to the CPU before transforming it into NumPy object
"""

# Following is an example when the torch.tensor was initially on the GPU
# Feel free to skip this part for the moment

if torch.cuda.is_available(): # On Apple's M1 chip it will be False
                              # On Google Colab, if you are not using T4 GPU it will be False too
    device = torch.device("cuda") # "device" object now represents GPU (CUDA stands for NVIDIA's GPUs)
    x = torch.ones(5, device=device) # x is on "cuda" (GPU) now
    # here doing x.numpy() will return error as NumPy can't handle data on GPU
    x = x.to("cpu") # moving x to cpu before transform
    numpy_x = x.numpy()


tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
<class 'numpy.ndarray'>
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
"""
There are situations where we want to make sure the original NumPy data remains intact.
In this case, we can directly use torch.tensor or torch.FloatTensor to create new copies
instead of using `.from_numpy`, which shares memory with the original NumPy array.
"""
import torch
import numpy as np
a = np.array([1, 2, 3])
print(a)

b = torch.tensor(a, dtype=torch.float32)  # Creates a new copy
c = torch.FloatTensor(a)  # Also creates a new copy
print(b)
b += 1
c += 1

print(a)  # NumPy array `a` remains unchanged
print(b)  # Tensor `b` is modified
print(c)  # Tensor `c` is modified

"""
Alternatively, `.clone()` is a commonly used method to make an independent copy of a tensor.
"""

b = torch.from_numpy(a)  # Shares memory with `a`
# If we modify `b` now, the values in `a` will also be affected.
b = b.clone()  # We make a copy and assign it to `b`
b += 1

print(a)  # `a` is not influenced after cloning
print(b)  # `b` is modified independently

# Note: just keep in mind first here that the .clone() method do preserve the computational graph.
# For NumPy array, the function to make a copy is `.copy()`, e.g., try a.copy().


[1 2 3]
tensor([1., 2., 3.])
[1 2 3]
tensor([2., 3., 4.])
tensor([2., 3., 4.])
[1 2 3]
tensor([2, 3, 4])


# From the next tutorial, we will start exploring the power of PyTorch tensors. How can we leverage this power? What sets PyTorch apart from just using NumPy?
